# Generated by Django 5.1.4 on 2024-12-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='Product',
        ),
    ]
