# Generated by Django 5.1.4 on 2025-01-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0004_rename_name_product_brand_product_amp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
