# Generated by Django 5.1.4 on 2025-01-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='product',
            new_name='car',
        ),
    ]
