# Generated by Django 5.1.4 on 2025-01-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_store', '0010_rename_product_carimages_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
