# Generated by Django 5.1.4 on 2025-01-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
